In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import sys
import json
from pathlib import Path

os.chdir("/home/kaariaa3/mscthesis/")
sys.path.append("./src/")  # Add module directory to path

import pandas as pd
import numpy as np

from utils.plots import calculate_metrics, calculate_accuracy
from utils.tools import get_config, collect_jobs, prettify_table, format_table, aggregate_results
from utils.constants import PRED_COLS, THEME_TO_TOPICS_MAPPING, CONCEPT_TO_CHAPTER_MAPPING

In [11]:
cols = [
    "model",
    "use_instructions",
    "type_of_demonstrations",
    "number_of_demonstrations",
    "num_rows",
    "num_parse_errors",
    "num_gen_errors",
    #*PRED_COLS
]

def error_stats_table(jobs, cols):

    print(f"Processing {len(jobs)} jobs.")

    total_rows = 0
    table = {col_name: [] for col_name in cols}
    for job in jobs:
        df = pd.read_csv(job["result_csv"], sep=";")
        num_rows = len(df)
        total_rows += num_rows

        # LLM failed to produce proper json
        mask_no_errors = (df[PRED_COLS] != "\"PARSE ERROR\"").all(axis=1)
        df = df[mask_no_errors]
        num_parse_errors = list(mask_no_errors).count(False)

        # LLM did not follow instructions
        mask_generate_fail = df[PRED_COLS].isin(["\"yes\"", "\"no\""]).all(axis=1)
        df = df[mask_generate_fail]
        num_gen_errors = list(mask_generate_fail).count(False)

        config = get_config(job["config_json"])

        # Append run configs
        table["model"].append(job["model"])
        table["use_instructions"].append(config["use_instructions"])
        table["type_of_demonstrations"].append(config["type_of_demonstrations"])
        table["number_of_demonstrations"].append(config["number_of_demonstrations"])

        # Append error counts
        table["num_rows"].append(num_rows)
        table["num_parse_errors"].append(num_parse_errors)
        table["num_gen_errors"].append(num_gen_errors)

    return table, total_rows

def error_df(jobs, cols):

    print(f"Processing {len(jobs)} jobs.")

    job_ids = []
    table = {col_name: [] for col_name in cols}
    for job in jobs:
        df = pd.read_csv(job["result_csv"], sep=";")
        num_rows = len(df)

        # LLM failed to produce proper json
        mask_generate_fail = ~df[PRED_COLS].isin(["\"yes\"", "\"no\""]).all(axis=1)
        df = df[mask_parse_errors | mask_generate_fail]

        config = get_config(job["config_json"])

        # Append run configs
        config_cols = cols[:4]
        for col in config_cols:
            table[col] = table[col] + [config[col]] * len(df)

        # Append pred
        for col in PRED_COLS:
            table[col] = table[col] + list(df[col])

    return table

In [4]:
def get_suite(row):

    n_demos = row["number_of_demonstrations"]
    type_demos = row["type_of_demonstrations"][0:3]
    instr = "impl" if row["use_instructions"] == "no" else "expl"

    return f"{n_demos}-{type_demos}-{instr}"

def capitalize(s):
    return s[0].upper() + s[1:]

def order_suites(strings):
    return sorted(strings, key=lambda s: (
        s.split('-')[2],  # implicit-excplict
        s.split('-')[0],  # num demos
        s.split('-')[1],  # demo type
    ))

def order_models(strings):
    return sorted(strings, key=lambda s: (
        int(s.split('-')[1][:-1]),  # Param count, B dropped
        #s.split('-')[0],  # Model name
    ), reverse=True)

In [5]:
# Collect raw data
basepath = "./outputs/v6"
finished_jobs = collect_jobs(basepath)
jobs_list = [job for _, job_list in finished_jobs.items() for job in job_list] # Flatten

#errs, rows = error_stats_table(jobs_list, cols)
#res = pd.DataFrame(errs)
#res = prettify_table(res)

In [13]:
errs = error_df(jobs_list, cols[:4] + PRED_COLS)

Processing 330 jobs.

In [25]:
pd.set_option('display.max_rows', 500)

err_df = pd.DataFrame(errs)

mask_parse_errors = (err_df[PRED_COLS] == "\"PARSE ERROR\"").any(axis=1)

err_df[~mask_parse_errors]

,model,use_instructions,type_of_demonstrations,number_of_demonstrations,themeCorrect,topicCorrect,usesAdditionalConcepts
0,Qwen/Qwen3-32B,0,-1,1,true,false,false
1,Qwen/Qwen3-32B,0,-1,1,true,true,false
2,Qwen/Qwen3-32B,0,-1,1,true,true,false
3,Qwen/Qwen3-32B,0,-1,1,true,true,false
4,Qwen/Qwen3-32B,0,-1,1,true,true,false
5,Qwen/Qwen3-32B,0,-1,1,true,true,false
6,Qwen/Qwen3-32B,0,-1,1,true,true,false
7,Qwen/Qwen3-32B,0,-1,1,true,false,false
8,Qwen/Qwen3-32B,0,-1,1,true,false,false
9,Qwen/Qwen3-32B,0,-1,1,true,true,false
10,Qwen/Qwen3-32B,0,-1,1,true,true,false
11,Qwen/Qwen3-32B,0,-1,1,true,true,false
12,Qwen/Qwen3-32B,0,-1,1,true,true,false
13,Qwen/Qwen3-32B,0,-1,1,true,true,false
14,Qwen/Qwen3-32B,0,-1,1,true,true,false
15,Qwen/Qwen3-32B,0,-1,1,true,true,false
16,Qwen/Qwen3-32B,0,-1,1,true,true,false
17,Qwen/Qwen3-32B,0,-1,1,true,true,false
18,Qwen/Qwen3-32B,0,-1,1,true,true,false
19,Qwen/Qwen3-32B,0,-1,1,true,true,false
20,Qwen/Qwen3-32B,0,-1,1,true,true,false
21,Qwen/Qwen3-32B,0,-1,1,true,true,false
22,Qwen/Qwen3-32B,0,-1,1,true,true,false
23,Qwen/Qwen3-32B,0,-1,1,true,false,false
24,Qwen/Qwen3-32B,0,-1,1,true,false,false
25,Qwen/Qwen3-32B,0,-1,1,true,true,false
26,Qwen/Qwen3-32B,0,-1,1,true,true,false
27,Qwen/Qwen3-32B,0,-1,1,true,true,false
28,Qwen/Qwen3-32B,0,-1,1,true,true,false
29,Qwen/Qwen3-32B,0,-1,1,true,true,false
30,Qwen/Qwen3-32B,0,-1,1,true,true,false
31,Qwen/Qwen3-32B,0,-1,6,true,true,false
32,Qwen/Qwen3-32B,0,-1,6,false,false,true
33,Qwen/Qwen3-32B,0,-1,6,true,true,false
34,Qwen/Qwen3-32B,0,-1,6,true,true,false
35,Qwen/Qwen3-32B,0,-1,6,true,true,false
36,Qwen/Qwen3-32B,0,-1,6,false,false,true
37,Qwen/Qwen3-32B,0,-1,6,false,false,false
38,Qwen/Qwen3-32B,0,-1,6,true,true,false
39,Qwen/Qwen3-32B,0,-1,6,true,true,false
40,Qwen/Qwen3-32B,0,-1,6,false,false,true
41,Qwen/Qwen3-32B,0,-1,6,true,true,false
42,Qwen/Qwen3-32B,0,-1,6,true,true,false
43,Qwen/Qwen3-32B,0,-1,6,true,true,false
44,Qwen/Qwen3-32B,0,-1,6,false,false,true
45,Qwen/Qwen3-32B,0,-1,6,false,false,true
46,Qwen/Qwen3-32B,0,-1,6,true,true,false
47,Qwen/Qwen3-32B,0,-1,6,true,true,false
48,Qwen/Qwen3-32B,0,-1,6,true,true,false
49,Qwen/Qwen3-32B,0,-1,6,false,false,true
50,Qwen/Qwen3-32B,0,-1,6,true,true,false
51,Qwen/Qwen3-32B,0,-1,6,true,true,false
52,Qwen/Qwen3-32B,0,-1,6,true,true,false
53,Qwen/Qwen3-32B,0,-1,6,true,true,false
54,Qwen/Qwen3-32B,0,-1,6,false,false,true
55,Qwen/Qwen3-32B,0,-1,6,false,false,true
56,Qwen/Qwen3-32B,0,-1,6,true,true,false
57,Qwen/Qwen3-32B,0,-1,6,true,true,false
58,Qwen/Qwen3-32B,0,-1,6,true,true,false
59,Qwen/Qwen3-32B,0,-1,6,true,true,false
60,Qwen/Qwen3-32B,0,-1,6,true,true,false
61,Qwen/Qwen3-32B,0,-1,6,true,true,false
62,Qwen/Qwen3-32B,0,-1,6,false,false,false
63,Qwen/Qwen3-32B,0,-1,6,true,true,false
64,Qwen/Qwen3-32B,0,-1,6,true,true,false
65,Qwen/Qwen3-32B,0,-1,6,true,true,false
66,Qwen/Qwen3-32B,0,-1,6,false,false,true
67,Qwen/Qwen3-32B,0,-1,6,true,true,false
68,Qwen/Qwen3-32B,0,-1,6,true,true,false
69,Qwen/Qwen3-32B,0,-1,6,true,true,false
70,Qwen/Qwen3-32B,0,-1,6,true,true,false
71,Qwen/Qwen3-32B,0,-1,6,false,false,false
72,Qwen/Qwen3-32B,0,-1,6,true,true,false
73,Qwen/Qwen3-32B,0,-1,6,true,true,false
74,Qwen/Qwen3-32B,0,-1,6,true,true,false
75,Qwen/Qwen3-32B,0,-1,6,true,true,false
76,Qwen/Qwen3-32B,0,-1,6,true,true,false
77,Qwen/Qwen3-32B,0,-1,6,true,true,false
78,Qwen/Qwen3-32B,0,-1,6,true,true,false
79,Qwen/Qwen3-32B,0,-1,6,true,true,false
80,Qwen/Qwen3-32B,0,-1,6,true,true,false
81,Qwen/Qwen3-32B,0,-1,6,true,true,false
82,Qwen/Qwen3-32B,0,-1,6,true,true,false
83,Qwen/Qwen3-32B,0,-1,6,true,true,false
84,Qwen/Qwen3-32B,0,-1,6,true,true,false
85,Qwen/Qwen3-32B,0,-1,6,true,true,false
86,Qwen/Qwen3-32B,0,-1,6,true,true,false
87,Qwen/Qwen3-32B,0,-1,6,false,false,true
88,Qwen/Qwen3-32B,0,-1,6,true,true,false
89,Qwen/Qwen3-32B,0,-1,6,true,true,false
90,Qwen/Qwen3-32B,0,-1,6,true,true,false
91,Qwen/Qwen3-32B,0,-1,6,true,true,false
92,Qwen/Qwen3-32B,0,-1,6,true,true,false
93,Qwen/Qwen3-32B,0,-1,6,true,true,false
94,Qwen/Qwen3-32B,0,-1,6,true,true,false
95,Qwen/Qwen3-32B,0,-1,6,true,true,false
96,Qwen/Qwen3-32B,0,-1,6,false,false,true
97,Qwen/Qwen3-32B,0,-1,6,false,false,true
98,Qwen/Qwen3-32B,0,-1,6,false,false,true
99,Qwen/Qwen3-32B,0,-1,6,true,true,false
100,Qwen/Qwen3-32B,0,-1,6,true,true,false
101,Qwen/Qwen3-32B,0,-1,6,true,true,false
102,Qwen/Qwen3-32B,0,-1,6,true,true,false
103,Qwen/Qwen3-32B,0,-1,6,true,true,false
104,Qwen/Qwen3-32B,0,-1,6,true,true,false
105,Qwen/Qwen3-32B,0,-1,6,true,true,false
106,Qwen/Qwen3-32B,0,-1,6,false,false,true
107,Qwen/Qwen3-32B,0,-1,6,false,false,false
108,Qwen/Qwen3-32B,0,-1,6,true,true,false
109,Qwen/Qwen3-32B,0,-1,6,true,true,false
110,Qwen/Qwen3-32B,0,-1,6,true,true,false
111,Qwen/Qwen3-32B,0,-1,6,true,true,false
112,Qwen/Qwen3-32B,0,-1,6,true,false,false
113,Qwen/Qwen3-32B,0,-1,6,true,true,false
114,Qwen/Qwen3-32B,0,-1,6,false,false,false
115,Qwen/Qwen3-32B,0,-1,6,true,true,false
116,Qwen/Qwen3-32B,0,-1,6,true,true,false
117,Qwen/Qwen3-32B,0,-1,6,false,false,true
118,Qwen/Qwen3-32B,0,-1,6,true,true,false
119,Qwen/Qwen3-32B,0,-1,6,true,true,false
120,Qwen/Qwen3-32B,0,-1,6,true,true,false
121,Qwen/Qwen3-32B,0,-1,6,true,true,false
122,Qwen/Qwen3-32B,0,-1,6,true,true,false
123,Qwen/Qwen3-32B,0,-1,6,false,false,true
124,Qwen/Qwen3-32B,0,-1,6,false,false,true
125,Qwen/Qwen3-32B,0,-1,6,true,true,false
126,Qwen/Qwen3-32B,0,-1,6,true,true,false
127,Qwen/Qwen3-32B,0,-1,6,false,false,false
128,Qwen/Qwen3-32B,0,-1,6,true,true,false
129,Qwen/Qwen3-32B,0,-1,6,true,true,false
130,Qwen/Qwen3-32B,0,-1,6,true,true,false
131,Qwen/Qwen3-32B,0,-1,6,true,true,false
132,Qwen/Qwen3-32B,0,-1,6,true,true,false
133,Qwen/Qwen3-32B,0,-1,6,false,false,false
134,Qwen/Qwen3-32B,0,-1,6,true,true,false
135,Qwen/Qwen3-32B,0,-1,6,true,true,false
136,Qwen/Qwen3-32B,0,-1,6,true,true,false
137,Qwen/Qwen3-32B,0,-1,6,true,true,false
138,Qwen/Qwen3-32B,0,-1,6,true,true,false
139,Qwen/Qwen3-32B,0,-1,6,true,true,false
140,Qwen/Qwen3-32B,0,-1,6,true,true,false
141,Qwen/Qwen3-32B,0,-1,6,false,false,true
142,Qwen/Qwen3-32B,0,-1,6,true,true,false
143,Qwen/Qwen3-32B,0,-1,6,false,false,true
144,Qwen/Qwen3-32B,0,-1,6,true,true,false
145,Qwen/Qwen3-32B,0,-1,6,true,true,false
146,Qwen/Qwen3-32B,0,-1,6,true,true,false
147,Qwen/Qwen3-32B,0,-1,6,true,true,false
148,Qwen/Qwen3-32B,0,-1,6,true,true,false
149,Qwen/Qwen3-32B,0,-1,6,true,true,false
150,Qwen/Qwen3-32B,0,-1,6,false,false,true
151,Qwen/Qwen3-32B,0,-1,6,false,false,true
152,Qwen/Qwen3-32B,0,-1,6,false,false,true
153,Qwen/Qwen3-32B,0,-1,6,true,true,false
154,Qwen/Qwen3-32B,0,-1,6,false,false,true
155,Qwen/Qwen3-32B,0,-1,6,true,true,false
156,Qwen/Qwen3-32B,0,-1,6,true,true,false
157,Qwen/Qwen3-32B,0,-1,6,true,true,false
158,Qwen/Qwen3-32B,0,-1,6,true,true,false
159,Qwen/Qwen3-32B,0,-1,6,true,true,false
160,Qwen/Qwen3-32B,0,-1,6,true,true,false
161,Qwen/Qwen3-32B,0,-1,6,false,false,true
162,Qwen/Qwen3-32B,0,-1,6,true,true,false
163,Qwen/Qwen3-32B,0,-1,6,false,false,true
164,Qwen/Qwen3-32B,0,-1,6,true,true,false
165,Qwen/Qwen3-32B,0,-1,6,true,true,false
166,Qwen/Qwen3-32B,0,-1,6,true,true,false
167,Qwen/Qwen3-32B,0,-1,6,true,true,false
168,Qwen/Qwen3-32B,0,-1,6,false,false,true
169,Qwen/Qwen3-32B,0,-1,6,true,true,false
170,Qwen/Qwen3-32B,0,-1,6,true,true,false
171,Qwen/Qwen3-32B,0,-1,6,true,true,false
172,Qwen/Qwen3-32B,0,-1,6,true,true,false
173,Qwen/Qwen3-32B,0,-1,6,false,false,true
174,Qwen/Qwen3-32B,0,-1,6,true,true,false
175,Qwen/Qwen3-32B,0,-1,6,true,true,false
176,Qwen/Qwen3-32B,0,-1,6,true,true,false
177,Qwen/Qwen3-32B,0,-1,6,true,true,false
178,Qwen/Qwen3-32B,0,-1,6,true,true,false
179,Qwen/Qwen3-32B,0,-1,6,false,false,true
180,Qwen/Qwen3-32B,0,-1,6,true,true,false
991,mistralai/Mistral-7B-Instruct-v0.3,0,1,6,"""yes""","""yes""","""for loop"""
995,mistralai/Mistral-7B-Instruct-v0.3,0,1,6,"""yes""","""yes""","""while loop"""
996,mistralai/Mistral-7B-Instruct-v0.3,0,1,6,"""yes""","""yes""","""for loop, conditional statements"""
997,mistralai/Mistral-7B-Instruct-v0.3,0,1,6,"""yes""","""yes""","""for loop, switch statement"""
998,mistralai/Mistral-7B-Instruct-v0.3,0,1,6,"""yes""","""yes""","""for loop"""
999,mistralai/Mistral-7B-Instruct-v0.3,0,1,6,"""yes""","""yes""","""while loop"""
1020,mistralai/Mistral-7B-Instruct-v0.3,0,1,6,"""yes""","""yes""","""for loop, conditional statements, logical ope..."
1067,mistralai/Mistral-7B-Instruct-v0.3,0,1,6,"""yes""","""yes""","""for loop, conditional statements, logical ope..."
1068,mistralai/Mistral-7B-Instruct-v0.3,0,1,6,"""yes""","""yes""","""while loop, user input, program output, varia..."
1069,mistralai/Mistral-7B-Instruct-v0.3,0,1,6,"""yes""","""yes""","""while loop"""
1070,mistralai/Mistral-7B-Instruct-v0.3,0,1,6,"""yes""","""yes""","""while loop"""
1071,mistralai/Mistral-7B-Instruct-v0.3,0,1,6,"""yes""","""yes""","""for loop, switch statement"""
1159,mistralai/Mistral-7B-Instruct-v0.3,0,1,6,"""yes""","""yes""","""arithmetics"""
1160,mistralai/Mistral-7B-Instruct-v0.3,0,1,6,"""yes""","""yes""","""arithmetics"""
1161,mistralai/Mistral-7B-Instruct-v0.3,0,1,6,"""yes""","""yes""","""while loop, arithmetics"""
1162,mistralai/Mistral-7B-Instruct-v0.3,0,1,6,"""yes""","""yes""","""while loop"""
1163,mistralai/Mistral-7B-Instruct-v0.3,0,1,6,"""yes""","""yes""","""arithmetics"""
1164,mistralai/Mistral-7B-Instruct-v0.3,0,1,6,"""yes""","""yes""","""conditional statements"""

In [15]:
res = res.sort_values(by=["use_instructions", "number_of_demonstrations", "type_of_demonstrations"])
res["suite"] = res.apply(get_suite, axis=1)

,model,use_instructions,type_of_demonstrations,number_of_demonstrations,num_rows,num_parse_errors,num_gen_errors,suite
1,Qwen3-8B,no,negative,1,534,0,0,1-neg-impl
13,Qwen3-8B,no,negative,1,534,0,0,1-neg-impl
24,Qwen3-8B,no,negative,1,534,0,0,1-neg-impl
33,Qwen3-8B,no,negative,1,534,0,0,1-neg-impl
47,Qwen3-8B,no,negative,1,534,0,0,1-neg-impl
...,...,...,...,...,...,...,...,...
285,Mistral-Small-3.2-24B-Instruct-2506,yes,positive,6,529,0,0,6-pos-expl
296,Mistral-Small-3.2-24B-Instruct-2506,yes,positive,6,529,0,0,6-pos-expl
308,Mistral-Small-3.2-24B-Instruct-2506,yes,positive,6,529,1,0,6-pos-expl
317,Mistral-Small-3.2-24B-Instruct-2506,yes,positive,6,529,0,0,6-pos-expl
329,Mistral-Small-3.2-24B-Instruct-2506,yes,positive,6,529,0,0,6-pos-expl

In [44]:
# Show all columns
pd.options.display.max_columns = None
# Set float formatting
pd.options.display.float_format = '{:,.3f}'.format
bycols = [
    "model",
    "suite"
]

agg = aggregate_results(res, bycols, cols[5:], funs=["sum"])
# Drop count
# Drop rows with no errors
error_rows = (agg.loc[:, :] > 0).any(axis=1)
agg = agg[error_rows]

In [48]:
#formatted = format_table(agg)
formatted = agg.copy()

#formatted.columns = formatted.columns.get_level_values(0) # Flatten

#formatted = formatted.loc[["num_parse_errors", "num_gen_errors"],:]

parse_errs_sum = formatted["num_parse_errors"].sum()
gen_errs_sum = formatted["num_gen_errors"].sum()

#formatted.loc[("Total sum", "")] = (parse_errs_sum, gen_errs_sum) # Add total
#formatted.loc[("Error rate", "", "", "")] = (parse_errs_sum / rows, gen_errs_sum / rows) # Add total

print(parse_errs_sum)
print(gen_errs_sum)

print(parse_errs_sum / rows)
print(gen_errs_sum / rows)

sum    1054
dtype: int64
sum    199
dtype: int64
sum   0.006
dtype: float64
sum   0.001
dtype: float64

In [51]:
formatted.groupby(by="model").agg("sum")

                                    num_parse_errors num_gen_errors
                                                 sum            sum
model
Llama-3.1-8B-Instruct                            789              0
Llama-3.3-70B-Instruct                            18              0
Mistral-7B-Instruct-v0.3                         158             18
Mistral-Small-3.2-24B-Instruct-2506               88              0
Qwen3-32B                                          1            181

In [ ]:
tables_location = "./latex/tables"
os.makedirs(tables_location, exist_ok=True)
with open(f"{tables_location}/err_table.tex", "w", encoding="UTF-8") as f:
    text = formatted.to_latex(escape=True, sparsify=True)
    #f.write(text)